spring.application.name=WelcomeSpringBoot
server.port=8081

#
#develope functionally...
#
#requiremnt--> JIRA-546 (develope a share button)
#
#1. Local env.
#develope that functionality locally..   inside your machine.. (laptop)
#if works fine--> executes all test cases
#
#2. deploy these changes on dev env.. (dev server/cluster)
#testing: executes all test cases
#
#3. deploy on UAT env. (User Acceptance Testing)
#funtional testing/ regression testing on UAT--> Build -> package wlll be created with proper testing..
#
#testing will give sign -off:  JUly_rel_243535745
#
#18th-->  JUly_rel_243535745  PROD..    -->  testing  sat/sun..    Monday.
#COB-->it work